services:
  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    ports:
      - 9200:9200
    env_file: .env
    restart: on-failure
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -u elastic:$ELASTIC_PASSWORD --fail http://localhost:9200 || exit 1"
        ]
      interval: 1s
      timeout: 1s
      retries: 120
  chrono-backend:
    build: .
    ports:
      - 5000:5000
    env_file: .env
    restart: on-failure
    depends_on:
      search:
        condition: service_healthy
        restart: true
