services:
  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    env_file: .env
    ports:
      - ${ELASTIC_PORT}:9200
    restart: on-failure
    mem_limit: 1GB
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -u elastic:$ELASTIC_PASSWORD --fail http://localhost:9200 || exit 1"
        ]
      interval: 1s
      timeout: 1s
      retries: 120
    profiles:
      - dev
      - prod

  chrono-dev:
    build:
      context: .
      dockerfile: ./chrono/docker/dev/Dockerfile
    env_file: .env
    ports:
      - ${CHRONO_PORT}:${CHRONO_PORT}
    restart: on-failure
    depends_on:
      search:
        condition: service_healthy
    profiles:
      - dev

  chrono-prod:
    build:
      context: .
      dockerfile: ./chrono/docker/prod/Dockerfile
      args:
        - CHRONO_PORT=${CHRONO_PORT}
    env_file: .env
    ports:
      - ${CHRONO_PORT}:${CHRONO_PORT}
    restart: on-failure
    depends_on:
      search:
        condition: service_healthy
    profiles:
      - prod

networks:
  default:
    name: chrono_net
    external: true

volumes:
  elastic_data:
